export const serverInitialState: EntitiesPayload = {
    icons: [
        {
            id: 1,
            name: 'folder.png',
        },
        {
            id: 2,
            name: 'home.png',
        },
        {
            id: 3,
            name: 'work.png',
        },
        {
            id: 4,
            name: 'sport.png',
        },
    ],
    statuses: [
        {
            id: 1,
            status: 'низкий',
            color: '#808080',
        },
        {
            id: 2,
            status: 'нормальный',
            color: '#000000',
        },
        {
            id: 3,
            status: 'повышенный',
            color: '#008000',
        },
        {
            id: 4,
            status: 'высокий',
            color: '#ff0000',
        },
    ],
    categories: [
        {
            id: 1,
            icon_id: 3,
            category: 'Работа',
        },
        {
            id: 2,
            icon_id: 2,
            category: 'Дом',
        },
        {
            id: 3,
            icon_id: 4,
            category: 'Здоровье',
        },
        {
            id: 4,
            icon_id: 4,
            category: 'Фуфло',
        },
    ],
    todos: [
        {
            id: 1,
            status_id: 1,
            category_id: 1,
            todo: 'Todo1',
            description: undefined,
            due_date: undefined,
            completed: undefined,
            deleted: false,
        },
        {
            id: 2,
            status_id: 2,
            category_id: 2,
            todo: 'Hover your mouse over a project or item and click the icon on the right side of the item for more options',
            description: undefined,
            due_date: new Date('01/05/2023').valueOf(),
            completed: false,
            deleted: false,
        },
        {
            id: 3,
            status_id: 3,
            category_id: 3,
            todo: 'Todo3',
            description: undefined,
            due_date: new Date('05/08/2023').valueOf(),
            completed: true,
            deleted: false,
        },
        {
            id: 4,
            status_id: 4,
            category_id: 1,
            todo: 'Todo4',
            description: undefined,
            due_date: new Date('02/02/2023').valueOf(),
            completed: true,
            deleted: false,
        },
        {
            id: 5,
            status_id: 4,
            category_id: undefined,
            todo: 'Todo5',
            description: undefined,
            due_date: undefined,
            completed: false,
            deleted: false,
        },
        {
            id: 6,
            status_id: 4,
            category_id: undefined,
            todo: 'Todo6',
            description: undefined,
            due_date: undefined,
            completed: true,
            deleted: false,
        },
        {
            id: 7,
            status_id: 2,
            category_id: undefined,
            todo: 'Todo7',
            description: undefined,
            due_date: undefined,
            completed: true,
            deleted: true,
        },
    ],
};
