name: My todos

on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - master
        paths-ignore:
            - 'docs/**'
            - '**.md'
            - '.vscode/**'
            - '.eslint*.*'
            - '.gitignore'
            - '.huskyrc.js'
            - '.prettier*.*'
            - 'docker-stack.yml'
            - 'backups/**'
            - '.dockerignore'
            - '.editorconfig'
            - '.env.*'

permissions:
    contents: write # to fetch code (actions/checkout)

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Git Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              id: setup_node_step
              uses: actions/setup-node@v3
              with:
                  node-version: 'latest'

            - name: Enable Cache
              id: cache_step
              uses: actions/cache@v3
              with:
                  key: ${{ hashFiles('yarn.lock') }}
                  path: node_modules

            - if: ${{ steps.cache_step.outputs.cache-hit != 'true' }}
              run: yarn install --frozen-lockfile

            - name: lint
              run: yarn tsc

            - name: build
              run: yarn build

            - name: Check for changes in dist folder
              id: check_changes
              run: |
                  git diff HEAD
                  echo "::set-output name=has_changes::$(if [ $? -eq 1 ]; then echo 'true'; else echo 'false'; fi)"

            - name: Commit and push changes
              # if: steps.check_changes.outputs.has_changes == 'true'
              run: |
                  git config --local user.email "github-actions[bot]@github.com"
                  git config --local user.name "github-actions[bot]"
                  git add .
                  git commit -m "ci changes"
                  git push origin HEAD:refs/heads/${{ github.head_ref }} -f
