name: Build the project

on:
    push:
        branches: [main, master]
    pull_request:
        branches:
            - master
        paths-ignore:
            - 'docs/**'
            - '**.md'
            - '.vscode/**'
            - '.eslint*.*'
            - '.gitignore'
            - '.huskyrc.js'
            - '.prettier*.*'
            - 'docker-stack.yml'
            - 'backups/**'
            - '.dockerignore'
            - '.editorconfig'
            - '.env.*'
            - 'src/server/__tests__/**'

# permissions:
#     contents: write # to fetch code (actions/checkout)

jobs:
    build:
        # не выполняем при merge PR
        # if: ${{ github.event_name != 'push' && github.ref != 'refs/heads/master' }}
        timeout-minutes: 5

        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              id: setup_node_step
              uses: actions/setup-node@v3
              with:
                  node-version: 'latest'

            - name: Enable Cache
              id: cache_step
              uses: actions/cache@v3
              with:
                  key: ${{ hashFiles('yarn.lock') }}
                  path: node_modules

            - if: ${{ steps.cache_step.outputs.cache-hit != 'true' }}
              run: yarn install --frozen-lockfile

            - name: tslint
              run: yarn tsc

            - name: eslint
              run: yarn eslint

            - name: test
              run: yarn test

            - name: stylelint
              run: yarn stylelint

            - name: Install Playwright
              run: yarn playwright install --with-deps

            - name: Run Playwright tests
              run: yarn playwright test

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30

            - name: build
              run: yarn build
