name: Publish Pages

on:
    workflow_run:
        workflows: ['Build the project']
        types: [completed]
        branches: [master]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    publish_pages:
        runs-on: ubuntu-latest
        #  && github.event_name == 'push' && github.ref == 'refs/heads/master'
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        timeout-minutes: 5
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Git Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              id: setup_node_step
              uses: actions/setup-node@v3
              with:
                  node-version: 'latest'

            - name: Enable Cache
              id: cache_step
              uses: actions/cache@v3
              with:
                  key: ${{ hashFiles('yarn.lock') }}
                  path: node_modules

            - if: ${{ steps.cache_step.outputs.cache-hit != 'true' }}
              run: yarn install --frozen-lockfile

            - name: build
              run: yarn build

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Upload Pages Artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: docs/

            - name: Deploy Pages
              id: deployment
              uses: actions/deploy-pages@v2
