name: Publish Pages
on:
    workflow_run:
        workflows:
            - 'Playwright Tests'
            - 'Build the project'
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        timeout-minutes: 5

        needs: [Build the project, Playwright Tests]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: build
              run: yarn build

            - name: Upload Pages Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: pages
                  path: ./docs # Измените на директорию, где находятся собранные файлы

            - name: Deploy Pages
              uses: actions/deploy-pages@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifact-name: pages
