name: Publish Pages

on:
    push:
        branches: master

jobs:
    empty-job:
        runs-on: ubuntu-latest
        steps:
            - name: Do nothing
              run: |
                  echo "This is an empty job"
                  echo ${{ github.event_name == 'push' }}
                  echo ${{ github.ref == 'refs/heads/master' }}

jobы:
    build:
        runs-on: ubuntu-latest
        needs: ['Playwright Tests', 'Build the project']
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        timeout-minutes: 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: build
              run: yarn build

            - name: Upload Pages Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: pages
                  path: ./docs # Измените на директорию, где находятся собранные файлы

            - name: Deploy Pages
              uses: actions/deploy-pages@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifact-name: pages
