name: Publish Pages

on:
    workflow_run:
        workflows: ['Build the project', 'Playwright Tests']
        types: [completed]
        branches: [master]

permissions:
    contents: write # to fetch code (actions/checkout)

jobs:
    publish:
        runs-on: ubuntu-latest
        #  && github.event_name == 'push' && github.ref == 'refs/heads/master'
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        timeout-minutes: 5

        steps:
            - name: Git Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              id: setup_node_step
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Enable Cache
              id: cache_step
              uses: actions/cache@v3
              with:
                  key: ${{ hashFiles('yarn.lock') }}
                  path: node_modules

            - if: ${{ steps.cache_step.outputs.cache-hit != 'true' }}
              run: yarn install --frozen-lockfile

            - name: build
              run: yarn build

            - name: Upload Pages Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: pages
                  path: ./docs # Измените на директорию, где находятся собранные файлы

            - name: Deploy Pages
              uses: actions/deploy-pages@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifact-name: pages

    empty-job:
        runs-on: ubuntu-latest
        steps:
            - name: Do nothing
              run: |
                  echo ${{ github.event_name }}
                  echo ${{ github.ref }}
                  echo ${{ github.event.workflow_run.conclusion }}
