name: Playwright Tests
on:
    # push:
    #     branches: [main, master]
    pull_request:
        types:
            - opened
            - edited
        branches: [main, master]
        paths-ignore:
            - 'docs/**'
            - '**.md'
            - '.vscode/**'
            - '.eslint*.*'
            - '.gitignore'
            - '.huskyrc.js'
            - '.prettier*.*'
            - 'docker-stack.yml'
            - 'backups/**'
            - '.dockerignore'
            - '.editorconfig'
            - '.env.*'

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 'latest'

            - name: Enable Cache
              id: cache_step
              uses: actions/cache@v3
              with:
                  key: ${{ hashFiles('yarn.lock') }}
                  path: node_modules

            - if: ${{ steps.cache_step.outputs.cache-hit != 'true' }}
              run: yarn install --frozen-lockfile

            - name: Install Playwright Browsers
              run: yarn playwright install --with-deps

            - name: Run Playwright tests
              run: yarn playwright test

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
