# https://playwrightsolutions.com/playwright-github-action-to-cache-the-browser-binaries/

name: Playwright Tests

on:
    push:
        branches: [main, master]
    pull_request:
        types:
            - opened
        branches: [main, master]
        paths-ignore:
            - 'docs/**'
            - '**.md'
            - '.vscode/**'
            - '.eslint*.*'
            - '.gitignore'
            - '.huskyrc.js'
            - '.prettier*.*'
            - 'docker-stack.yml'
            - 'backups/**'
            - '.dockerignore'
            - '.editorconfig'
            - '.env.*'

jobs:
    test:
        # if: ${{ github.ref != 'refs/heads/master' }}
        timeout-minutes: 5

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Get installed Playwright version
              id: playwright-version
              run: |
                  echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'].slice(1))")" >> $GITHUB_ENV

            - name: Cache Node modules
              id: npm_cache
              uses: actions/cache@v3
              with:
                  key: nm-pw-${{ hashFiles('yarn.lock') }}
                  path: |
                      node_modules
                      ${{ github.workspace }}/ms-playwright

            - if: ${{ steps.npm_cache.outputs.cache-hit != 'true' }}
              run: yarn install --frozen-lockfile

            - if: ${{ steps.npm_cache.outputs.cache-hit != 'true' }}
              run: npx playwright install --with-deps

            - if: ${{ steps.npm_cache.outputs.cache-hit != 'true' }}
              run: npx playwright install-deps

            - name: Run Playwright tests
              run: yarn playwright test

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
